services:
  pg:
    image: postgres:18.0
    restart: always
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "weather"
    ports:
      - "54321:5432"